// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Base} from "./helpers/Base.sol";

/// @notice End-to-end: license holder earns 70% of the fees generated by traders on their commodity,
///         then sells the license and the buyer earns going forward.
contract IntegrationTest is Base {
    uint256 internal corn;

    function setUp() public override {
        super.setUp();
        corn = _listDefault("CORN", "Agricultural", 10, 500);
        _post(corn, 440e8);
        _fundPool(500 ether);
    }

    function test_licenseHolderEarnsFees_thenSellsRight() public {
        // Alice mints the CORN license.
        vm.prank(alice);
        nft.mint{value: 0.02 ether}(corn);
        assertEq(nft.ownerOf(corn), alice);

        // Bob trades CORN a lot: open + close several positions, generating open/close fees.
        for (uint256 i = 0; i < 5; i++) {
            vm.prank(bob);
            uint256 pid = engine.openPosition{value: 2 ether}(corn, true, 5, 0); // notional 10
            vm.prank(bob);
            engine.closePosition(pid, 0);
        }

        // Each round: openFee + closeFee = 10e18 * (10+10)bps = 0.02 ether of fees, 70% to holder.
        // 5 rounds => ~0.1 ether fees => ~0.07 ether to alice's bucket.
        uint256 bucket = feeManager.commodityBucket(corn);
        assertApproxEqAbs(bucket, 0.07 ether, 1e14);

        // Alice claims her 70%.
        uint256 aliceBefore = alice.balance;
        vm.prank(alice);
        feeManager.claim(corn);
        assertApproxEqAbs(alice.balance - aliceBefore, 0.07 ether, 1e14);

        // Protocol has its 30% (plus 30% of the pre-claim fees).
        assertGt(feeManager.protocolFees(), 0);
        uint256 tBefore = treasury.balance;
        feeManager.withdrawProtocolFees();
        assertGt(treasury.balance - tBefore, 0);

        // Alice sells the license to bob.
        vm.prank(alice);
        nft.transferFrom(alice, bob, corn);
        assertEq(nft.ownerOf(corn), bob);

        // More trading happens; new fees accrue to bob now.
        vm.prank(alice); // alice trades this time
        uint256 pid2 = engine.openPosition{value: 2 ether}(corn, false, 5, 0);
        vm.prank(alice);
        engine.closePosition(pid2, 0);

        uint256 bobBucket = feeManager.commodityBucket(corn);
        assertGt(bobBucket, 0);

        uint256 bobBefore = bob.balance;
        vm.prank(bob);
        feeManager.claim(corn);
        assertApproxEqAbs(bob.balance - bobBefore, bobBucket, 1);
    }

    function test_poolProfitsWhenTradersLoseNet() public {
        uint256 shareBefore = pool.sharePriceE18();

        // Trader opens a long then price falls: trader loses, pool gains.
        vm.prank(bob);
        uint256 pid = engine.openPosition{value: 5 ether}(corn, true, 4, 0); // notional 20
        _post(corn, 418e8); // -5% => loss ~1 ether to pool
        vm.prank(bob);
        engine.closePosition(pid, 0);

        assertGt(pool.sharePriceE18(), shareBefore);
    }
}
